services:
  - type: web
    name: mindspace-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: startCommand: python run.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: MINDSPACE_SECRET_KEY
        sync: false